name: fp_mobile
description: "Notes App using Firebase & Firestore as Backend"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  scoped_model: ^2.0.0

  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.1
  transparent_image: ^2.0.1

  location: ^5.0.0
  geocoding: ^2.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

