// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCzezIpUq8r2eVwJP3gbScfAsuPUIFAiA',
    appId: '1:693454391977:web:640df92af37dc9acd977b8',
    messagingSenderId: '693454391977',
    projectId: 'todolist-81d54',
    authDomain: 'todolist-81d54.firebaseapp.com',
    storageBucket: 'todolist-81d54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDINYjntbAXfor40lxNl9R9F8RR9fR9FG4',
    appId: '1:693454391977:android:767cc4ad597aadabd977b8',
    messagingSenderId: '693454391977',
    projectId: 'todolist-81d54',
    storageBucket: 'todolist-81d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqzrnB1xa7iGWWvnSeqiai_OBkuR_1N24',
    appId: '1:693454391977:ios:631fc9071943e49ed977b8',
    messagingSenderId: '693454391977',
    projectId: 'todolist-81d54',
    storageBucket: 'todolist-81d54.appspot.com',
    iosBundleId: 'com.example.fpMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqzrnB1xa7iGWWvnSeqiai_OBkuR_1N24',
    appId: '1:693454391977:ios:631fc9071943e49ed977b8',
    messagingSenderId: '693454391977',
    projectId: 'todolist-81d54',
    storageBucket: 'todolist-81d54.appspot.com',
    iosBundleId: 'com.example.fpMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCzezIpUq8r2eVwJP3gbScfAsuPUIFAiA',
    appId: '1:693454391977:web:dd62fb04717cc2e4d977b8',
    messagingSenderId: '693454391977',
    projectId: 'todolist-81d54',
    authDomain: 'todolist-81d54.firebaseapp.com',
    storageBucket: 'todolist-81d54.appspot.com',
  );
}
